### ISSUE TITLE
flat tax doesnt work

### ISSUE THREAD

**Issue by iSeitan** [Indyuce/bounty-hunters#120]
i made it so when a player use a bounty on a player it remove a flat amount for tax of 1$
But when the player create the bounty he doesnt lose the 1$

**Comment by Indyuce** [comment]
You can edit that in the config.yml

```
bounty-tax:

  # Tax taken when creating a bounty (to fight abuse).
  # In % of the money reward + a flat tax amount
  bounty-creation:
    flat: 0
    scale: 15

```
