### ISSUE TITLE
Running commands on auto bounty does not work

### ISSUE THREAD

**Issue by ValhallaCraft** [Indyuce/bounty-hunters#122]
When I try to run a command on auto-bounty it does not run. 

```# Commands sent by the console when a player claims a bounty.
# {target} returns the target's name and {player} the claimer's
# name. Commands support PlaceholderAPI placeholders.
bounty-commands:

  # When a player claims a bounty.
  claim: [ ]
  # - '/give {player} minecraft:diamond 10'
  # - '/tell {target} Someone claimed your bounty.'

  # When a bounty is placed. {reward}
  place:
    player: [ ]
    console: [ ]
    # When a player kills another player illegaly.
    auto-bounty: [ ]
     - '/eco take {player} 100'
```

**Comment by Indyuce** [comment]
This worked for me
```
# Commands sent by the console when a player claims a bounty.
# {target} returns the target's name and {player} the claimer's
# name. Commands support PlaceholderAPI placeholders.
bounty-commands:

  # When a player claims a bounty.
  claim: [ ]
  # - '/give {player} minecraft:diamond 10'
  # - '/tell {target} Someone claimed your bounty.'

  # When a bounty is placed. {reward}
  place:
    player: [ ]
    console: [ ]
    # When a player kills another player illegaly.
    auto-bounty:
    - 'broadcast Who {target} died because of {player}'

  # When a bounty is increased by {amount}
  increase:
    player: [ ]
    console: [ ]
    # When a player kills another player illegaly.
    auto-bounty: [ ]
```

Try running the same setup and make sure it's not an issue with the command you run
