### ISSUE TITLE
Non OP players can't buy compass

### ISSUE THREAD

**Issue by Mangaboy5398** [Indyuce/bounty-hunters#50]
Hello!

Sorry if this is a stupid question but I couldn't find the answer in the wiki.

Normal players in my server can't seem to buy compasses. Says they don't have enough permissions. I'm not sure what node this is related to or what value the `permissions` setting in the config should be set to enable it.

I'm running it on Spigot 1.16.1, BountyHunters 2.2.6

Thanks!

**Comment by BboyZeroOne** [comment]
Seems like they can't use /bounty or /bounties command too even if they have the permission.

**Comment by Mangaboy5398** [comment]
> Seems like they can't use /bounty or /bounties command too even if they have the permission.

They can. They can open the gui, claim bounties, everything. Just when right clicking the compass. They say They don't have enough permissions.

Only if I give them the admin permission node can they buy. Maybe I set it up wrong?

**Comment by BboyZeroOne** [comment]
> > Seems like they can't use /bounty or /bounties command too even if they have the permission.
> 
> They can. They can open the gui, claim bounties, everything. Just when right clicking the compass. They say They don't have enough permissions.
> 
> Only if I give them the admin permission node can they buy. Maybe I set it up wrong?

As for mine, I'm running on 1.15.2. They are unable to use the command. 

I believe if you gave all the correct player commands, it **_should_** work as intended. If not, its a bug,

**Comment by Mangaboy5398** [comment]
> > > Seems like they can't use /bounty or /bounties command too even if they have the permission.
> > 
> > 
> > They can. They can open the gui, claim bounties, everything. Just when right clicking the compass. They say They don't have enough permissions.
> > Only if I give them the admin permission node can they buy. Maybe I set it up wrong?
> 
> As for mine, I'm running on 1.15.2. They are unable to use the command.
> 
> I believe if you gave all the correct player commands, it **_should_** work as intended. If not, its a bug,

Yeah I guess. I'm just not sure exactly what permission I should give them. Because the rest of the plugin works like a charm.

**Comment by BboyZeroOne** [comment]
If you give them **bountyhunters.compass** , then it should work.

He did not list the permission on the plugin page nor wiki but luckperms detected the permission.

**Comment by Mangaboy5398** [comment]
I just tried it and it didn't work unfortunately.

**Comment by BboyZeroOne** [comment]
Then I believe it is a bug haha

**Comment by Mangaboy5398** [comment]
Yep. Haha

**Comment by Indyuce** [comment]
I have no idea why I made this a configurable option, but you need to define that permission in the main plugin config file. This will be changed in the next build

```
# Player tracking lets player use a tracking compass to hunt
# down their bounty target. On the one hand, it gives an
# advantage to the hunters because they can find the player, but
# it also lets the target know how many players are tracking him.
player-tracking:
    enabled: true
    
    # Permission needed to track a
    # player and to buy the compass.
    permission: ''
```
